### PR TITLE
Palindrome Checker 

### PR DESCRIPTION
**Pull request by Orzala-2024**
⁂ This is a Palindrome checker created using html,css and js .
this repo contains below files:
-index.html
-styles.css
-script.js
-linters

♦I set dark mode to my project as well . below you can have a view of both light and dark mode of my project:

black-plaindrome

white-palindrome

### CODE REVIEW

**Comment by Orzala-2024** [comment]
@hamas2000 kindly view my project.

**Comment by Hamas2000** [comment]
@LimaSahibzada Dear Lima you have done a great job. 
1. your codes passed the freecodecamp requirements.
2. you have implemented a good design to your project. 
3. you do not have linter issue. 
4. your code is clean. 
BUT, you forgot to add readme details. Your readme.md file is empty. 
Good luck!

**Comment by Orzala-2024** [comment]
@Hamas2000 ,
Dear Hamasa , i added readme file . check my project plz.

**Comment by Orzala-2024** [comment]
@Hamas2000 ,
dear Hamasa , I added readme file to repo . check my project plz.

**Comment by Orzala-2024** [comment]
@Hamas2000 ,
check my project plz.

**Comment by Hamas2000** [comment]
@LimaSahibzada Dear Lima, you did a great job with the project. especially, the dark mode and light mode. 
So, I should say it was great and approved according to me.

**Review by ahzamir — APPROVED** [review]
### Hi @ORZALA-MS 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF (2)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your repo has a professional README.md file
✔️Your code is clean
✔️Your design is impressive and responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
